// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvlwzjwhkvvvkppyiczs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2bHd6andoa3Z2dmtwcHlpY3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDc2ODgsImV4cCI6MjA2NTgyMzY4OH0.0Qx7Xu8LDIUdY_69778MgYdA8GARFKYpD-9l1gtF9h0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);